pipeline {
    agent any

    environment {
        APP_NAME = "nodejs-app"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/vasutkar-0/Nodejs_Sample_Project.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${APP_NAME}:${IMAGE_TAG} ."
            }
        }

        stage('Deploy on Jenkins Server') {
            steps {
                sh """
                # Stop previous container if exists
                docker stop ${APP_NAME} || true
                docker rm ${APP_NAME} || true

                # Run new container
                docker run -d \
                  --name ${APP_NAME} \
                  -p 3000:3000 \
                  --restart always \
                  ${APP_NAME}:${IMAGE_TAG}
                """
            }
        }
    }

    post {
        success {
            echo "Deployment successful! App running at http://172.25.3.110/:3000"
        }
        failure {
            echo "Pipeline failed!"
        }
    }
}
